### PR TITLE
Automated Docs Generation on Linux

### PR DESCRIPTION
**Pull request by danoli3**
- Changes from OSX

Build Log (From Test on Danoli3/Openframeworks/Master)
https://travis-ci.org/danoli3/openFrameworks/jobs/71900197#L575

### CODE REVIEW

**Comment by danoli3** [comment]
Hmm I saw a travis warning

"This job ran on our legacy infrastructure. Please read our docs on how to upgrade"
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by bilderbuchi** [comment]
yes I know about this, but we can't switch this over to the new infra because we need sudo for the linux builds. Don't worry about this.
We can try if we can make single entries of the build matrix (i.e. only the docs build) use the new infrastructure.

**Comment by danoli3** [comment]
Okay cool. This is good to merge then for now.

**Comment by bilderbuchi** [comment]
can you put all the install commands in one line, i.e. `sudo apt-get install python-software-properties doxygen ncftp;`?

**Comment by danoli3** [comment]
All in one line see new commit

**Comment by bilderbuchi** [comment]
thanks, great!

**Pull request merged**
